wandb_version: 1

experiment_name:
  desc: null
  value: temporary_augmentation_2.0_testing
learning_rate:
  desc: null
  value: 0.00016
epochs:
  desc: null
  value: 100000
batch_size:
  desc: null
  value: 32
weight_decay:
  desc: null
  value: 0.0001
seed:
  desc: null
  value: 41
num_workers:
  desc: null
  value: 16
_wandb:
  desc: null
  value:
    python_version: 3.7.16
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1692356484.794528
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 14
      - 16
      - 23
      4: 3.7.16
      5: 0.15.8
      8:
      - 5
